---
execute:
  echo: true
  html:
    fig-width: 1050
    fig-height: 700
  pdf:
    fig-width: 7
    fig-height: 5
format:
  revealjs:
    width: 1050
    height: 700
    menu: false
    transition: slide
    auto-stretch: false
    embed-resources: true
    toc: false
    center: true
    slide-number: false
    preview-links: false
    footer: sebastiandres | https://sebastiandes.xyz
    output-file: "eng-slides"
---

## { .custom-section }
[Presentation tools <br> for Data Storytelling]{style="font-size: 2em"}

:::{.notes}
Presentation.
:::

---

## Presentation tools
* Oldies: PowerPoint
* Interactive: quarto, JupyterNotebook+RISE
* Other: revealjs, ...

:::{.notes}
Well, first of all, let’s review some different software tools we can use to create a presentation: Power Point, Quarto and JupyterNotebook+RISE. I know there are other alternatives, but these are the ones that I use and recommend. 
Death by PowerPoint: it’s not about the software per-se, but rather about the skills of the presenter.
:::

---

## Decision flow for the tools
Lorem Ipsum

:::{.notes}
PowerPoint: Use this if you have little time and need to create a presentation that’s disposable (one time effort). Might be the most configurable (design). Also, consider that you might need to share the file. Code is not executable nor properly formatted.
Quarto: Use this if you have enough time and you have a central subject with different “output sources” a book, a presentation, some lab reports, etc. You will be able to to easily copy-paste code, text and images, keeping things up to date easily. You can execute code and integrate the results on the presentation, but code is not executable on the presentation.
JupyterLab+RISE: Use this if you need to execute code live on the presentation and do not need much personalization.
Streamlit: You want to code something very interactive, closer to a webpage than to a presentation. You can spend a good amount of time tinkering and trying a half-crazy programmer (me).
:::

---

## Slide XX: Quarto + altair/vizzu: real time visualizations [5 mins]
Lorem Ipsum

:::{.notes}
Quarto is a well established project from . It allows to create an equivalent to jupyter notebook, but only with markdown, so the files and repos are clean and easy to maintain. The files have extension qmd, and you can create pretty much anything. Books, websites, etc. It’s quite incredible. This presentation has been made in quarto, BTW. For presentations, the configuration file takes care of converting the plain qmd files into a html page with the revealjs library, which as you have seen is highly editable. But, it’s just a website. So you can share it around and people should be able to open it without to much trouble - or convert it to pdf.
:::

---

## XX +1 
Lorem Ipsum

:::{.notes}
TBD
:::

---

## Jupyter Notebook + RISE + Python: real time code evaluation [5 mins]
Lorem Ipsum

:::{.notes}
I’m guessing we all know jupyter notebooks at this point. RISE is an extension that allows to convert a notebook into a presentation, while retaining the ability to execute the cells. It’s truly an amazing thing. 
:::

---

## XX +1 
Lorem Ipsum

:::{.notes}
TBD
:::